# -*- coding: utf-8 -*-
"""Project HAD5016H-XGBoost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0dK12DeyvQLyaOdslU70G3NlAR3aWRu

#Set up
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, accuracy_score
import warnings
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import TargetEncoder
#from category_encoders import TargetEncoder
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import StandardScaler
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import RocCurveDisplay, auc, roc_curve

#Validation section of tutorial
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold

warnings.filterwarnings('ignore')

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv("/content/drive/MyDrive/ML/Course Project/TMU_DM_808K_R1.csv") #Add your file path here

"""#Preprocessing"""

data.head()

#Checking if there are duplicates in Patients (a patient appears more than once)
data['Patient_ID'].is_unique

data['Patient_ID'].nunique()

"""There are 171619 patients with some patients having more than one visit"""

data.columns

#Descriptive Statistics for the Dataset
data.describe()

"""Finding the number of patients with or without diabetes"""

data['Diabetes'].value_counts()

#Subsetting the dataset to contain only patients with Diabetes
data = data[data['Diabetes'] == 1]

#Confirming if the subsetting has been done (Datasets for patients diabetes only)
data['Diabetes'].value_counts()

#Filtering out our interested features and label (DiabeticFootUlcer) into a new dataframe, df
df = data[['Patient_ID','Sex','A1c','FBS', 'duration_b_R1_[corticosteroid]_Days', 'duration_b_R1_[1stlineantidiabetic]_Days', 'duration_b_R1_[2ndline-antidiabetic]_Days'  ,'[DiabeticFootUlcer)']]
df = df.reset_index(drop=True)
df.head()

#Numerical Statistics of the dataset, df
df.describe()

#Checking for the null values in the dataset
df.isna().sum()

#Dropping the rows with null values in the Label since they cannot be determined
df.dropna(subset = ["[DiabeticFootUlcer)"], inplace=True)
df.head()

#A pie chart demonstrating class imbalance in the dataset
counts = df['[DiabeticFootUlcer)'].value_counts()

# Define colors
colors = ['#1c3a73', '#7cb1c2']

# Create pie chart
plt.figure(figsize=(6, 6)) #tuple for fig size, 6x6 inches
plt.pie(
    counts, #counts for each class
    labels=[f'{cls} ({count})' for cls, count in counts.items()],  # add labels with counts... counts.items() returns an iterable of tuples
                                                                    #e.g., [('class', count)], which are then unpacked and formatted into labels
    autopct='%1.1f%%',  # Show percentages
    colors=colors,
    startangle=90
)

# Set title
plt.title('Distribution of DiabeticFootUlcer', fontsize=14)

# Show plot
plt.show()

#Resetting the index
df = df.reset_index(drop=True)
df.head()

# Using the map() function to transform the 'Sex' column
df['Sex'] = df['Sex'].map({'Male': 0, 'Female': 1})
df

df['[DiabeticFootUlcer)'] = df['[DiabeticFootUlcer)'].astype(int)
df.dtypes

print(df.shape)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# 0) Make sure target is clean
# -----------------------------
df = df.copy()

target_col = "[DiabeticFootUlcer)"
unneeded_cols = ["Patient_ID"]

num_cols = [c for c in df.columns if c not in [target_col] + unneeded_cols]



# -----------------------------
# 1) Basic overview
# -----------------------------
print("Shape:", df.shape)
print("\nDtypes:\n", df.dtypes)
print("\nMissing values count:\n", df.isna().sum())
print("\nMissing values (%):\n", (df.isna().mean() * 100).round(2))

print("\nTarget distribution:")
print(df[target_col].value_counts(dropna=False))
print("\nTarget distribution (%):")
print((df[target_col].value_counts(dropna=False, normalize=True) * 100).round(2))

print("\nSummary stats (numeric):")
print(df[num_cols].describe().T)

# -----------------------------
# 2) Missingness bar plot
# -----------------------------
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)
missing_pct = missing_pct[missing_pct > 0]

if len(missing_pct) > 0:
    plt.figure()
    missing_pct.plot(kind="bar")
    plt.title("Missing Values (%) by Column")
    plt.ylabel("Percent Missing")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("\n✅ No missing values found in these columns.")

# -----------------------------
# 3) Distributions + Outliers (Boxplots)
# -----------------------------
# Histograms
for col in num_cols:
    plt.figure()
    x = df[col].dropna()
    plt.hist(x, bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.tight_layout()
    plt.show()

# Boxplots (outlier view)
for col in num_cols:
    plt.figure()
    x = df[col].dropna()
    plt.boxplot(x, vert=True)
    plt.title(f"Boxplot (Outliers) of {col}")
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

# -----------------------------
# 4) Outlier counts using IQR rule (numeric report)
# -----------------------------
def iqr_outlier_count(series: pd.Series):
    s = series.dropna()
    if len(s) < 4:
        return 0, np.nan, np.nan
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1
    lo = q1 - 1.5 * iqr
    hi = q3 + 1.5 * iqr
    outliers = ((s < lo) | (s > hi)).sum()
    return int(outliers), lo, hi

print("\nIQR-based outlier summary:")
for col in num_cols:
    out_ct, lo, hi = iqr_outlier_count(df[col])
    print(f"{col}: outliers={out_ct}, IQR-bounds=({lo:.3g}, {hi:.3g})")

# -----------------------------
# 5) DFU vs non-DFU comparison (Boxplots by class)
# -----------------------------
# (only if target has both classes)
if df[target_col].nunique(dropna=True) >= 2:
    for col in num_cols:
        plt.figure()
        # Prepare group arrays
        g0 = df.loc[df[target_col] == 0, col].dropna()
        g1 = df.loc[df[target_col] == 1, col].dropna()
        plt.boxplot([g0, g1], labels=["No DFU", "DFU"])
        plt.title(f"{col} by DFU status")
        plt.ylabel(col)
        plt.tight_layout()
        plt.show()

# -----------------------------
# 6) Collinearity: Correlation matrix + Heatmap
# -----------------------------
corr = df[num_cols].corr()

plt.figure()
plt.imshow(corr, aspect="auto")
plt.title("Correlation Heatmap (Numeric Features)")
plt.xticks(range(len(num_cols)), num_cols, rotation=45, ha="right")
plt.yticks(range(len(num_cols)), num_cols)
plt.colorbar()
plt.tight_layout()
plt.show()

print("\nCorrelation matrix:")
print(corr.round(3))

# Show highly correlated pairs
threshold = 0.8
high_pairs = []
cols = corr.columns
for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        val = corr.iloc[i, j]
        if abs(val) >= threshold:
            high_pairs.append((cols[i], cols[j], val))

if high_pairs:
    print(f"\nHighly correlated pairs (|r| >= {threshold}):")
    for a, b, v in sorted(high_pairs, key=lambda x: abs(x[2]), reverse=True):
        print(f"{a} vs {b}: r={v:.3f}")
else:
    print(f"\n✅ No feature pairs with |r| >= {threshold} in this subset.")

# -----------------------------
# 7) Quick pairwise scatter plots (small subset only)
# -----------------------------
# Helpful to visually see relationships (and weird clusters)
for i in range(len(num_cols)):
    for j in range(i+1, len(num_cols)):
        xcol, ycol = num_cols[i], num_cols[j]
        plt.figure()
        x = df[xcol]
        y = df[ycol]
        plt.scatter(x, y)
        plt.title(f"Scatter: {xcol} vs {ycol}")
        plt.xlabel(xcol)
        plt.ylabel(ycol)
        plt.tight_layout()
        plt.show()

# Correlation matrix to quantify relationships
corr_data = df[['A1c','FBS', 'duration_b_R1_[corticosteroid]_Days', 'duration_b_R1_[1stlineantidiabetic]_Days', 'duration_b_R1_[2ndline-antidiabetic]_Days'  ,'[DiabeticFootUlcer)']]
corr_matrix = corr_data.corr()
sns.heatmap(corr_matrix, annot=True, fmt=".2f")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency, mannwhitneyu

target_col = "[DiabeticFootUlcer)"

med_cols = [
    "total_b_R1_[2ndline-antidiabetic]_Records",
    "total_b_R1_[corticosteroid]_Records",
    "total_b_R1_[1stlineantidiabetic]_Records"
]

results = []

for col in med_cols:
    short_name = col.replace("total_b_R1_", "").replace("_Records", "")

    # Binary: any use vs no use
    data["_any_use"] = (data[col] > 0).astype(int)

    # --- Crosstab & proportions ---
    ct = pd.crosstab(data[target_col], data["_any_use"])
    ct.columns = ["No use", "Any use"]
    ct.index   = ["No DFU", "DFU"]

    prop_no_dfu = ct.loc["No DFU", "Any use"] / ct.loc["No DFU"].sum()
    prop_dfu    = ct.loc["DFU",    "Any use"] / ct.loc["DFU"].sum()

    # --- Chi-squared test (binary association) ---
    chi2, p_chi2, dof, expected = chi2_contingency(ct)

    # --- Relative risk ---
    rr = prop_dfu / prop_no_dfu if prop_no_dfu > 0 else np.nan

    # --- Odds ratio ---
    a = ct.loc["DFU",    "Any use"]
    b = ct.loc["DFU",    "No use"]
    c = ct.loc["No DFU", "Any use"]
    d = ct.loc["No DFU", "No use"]
    odds_ratio = (a * d) / (b * c) if (b * c) > 0 else np.nan

    # --- Mann-Whitney U on raw counts (non-parametric) ---
    g0 = data.loc[data[target_col] == 0, col].dropna()
    g1 = data.loc[data[target_col] == 1, col].dropna()
    u_stat, p_mwu = mannwhitneyu(g0, g1, alternative="two-sided")

    results.append({
        "Medication": short_name,
        "P(use | No DFU)": round(prop_no_dfu, 4),
        "P(use | DFU)":    round(prop_dfu, 4),
        "Diff (DFU - No DFU)": round(prop_dfu - prop_no_dfu, 4),
        "Relative Risk":   round(rr, 3),
        "Odds Ratio":      round(odds_ratio, 3),
        "Chi2 p-value":    round(p_chi2, 5),
        "Mann-Whitney p":  round(p_mwu, 5),
    })

    print(f"\n{'='*60}")
    print(f"{short_name}")
    print('='*60)
    print("\nContingency table:")
    print(ct)
    print(f"\nP(prescribed | No DFU) = {prop_no_dfu:.4f} ({prop_no_dfu*100:.1f}%)")
    print(f"P(prescribed | DFU)    = {prop_dfu:.4f} ({prop_dfu*100:.1f}%)")
    print(f"Difference             = {prop_dfu - prop_no_dfu:+.4f}")
    print(f"Relative Risk (RR)     = {rr:.3f}")
    print(f"Odds Ratio (OR)        = {odds_ratio:.3f}")
    print(f"Chi-squared p-value    = {p_chi2:.5f}")
    print(f"Mann-Whitney U p-value = {p_mwu:.5f}")

# Clean up temp column
data.drop(columns=["_any_use"], inplace=True)

# --- Summary table ---
res_df = pd.DataFrame(results)
print("\n\n" + "="*60)
print("SUMMARY TABLE")
print("="*60)
print(res_df.to_string(index=False))

# --- Visualization: Probability comparison ---
fig, ax = plt.subplots(figsize=(10, 5))

x = np.arange(len(res_df))
width = 0.35

bars1 = ax.bar(x - width/2, res_df["P(use | No DFU)"], width,
               label="No DFU", color="steelblue", edgecolor="black")
bars2 = ax.bar(x + width/2, res_df["P(use | DFU)"], width,
               label="DFU", color="salmon", edgecolor="black")

# Annotate with percentages
for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
            f"{bar.get_height()*100:.1f}%", ha="center", va="bottom", fontsize=10)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height(),
            f"{bar.get_height()*100:.1f}%", ha="center", va="bottom", fontsize=10)

ax.set_ylabel("Probability of Any Prescription")
ax.set_title("P(Prescribed Medication | DFU Status)")
ax.set_xticks(x)
ax.set_xticklabels(res_df["Medication"], rotation=15, ha="right")
ax.legend()
ax.set_ylim(0, min(1.0, res_df[["P(use | No DFU)", "P(use | DFU)"]].max().max() * 1.3))
plt.tight_layout()
plt.show()

# --- Visualization: Odds Ratios with reference line ---
fig, ax = plt.subplots(figsize=(8, 4))

ax.barh(res_df["Medication"], res_df["Odds Ratio"],
        color=["salmon" if o > 1 else "steelblue" for o in res_df["Odds Ratio"]],
        edgecolor="black")
ax.axvline(x=1, color="black", linestyle="--", linewidth=1, label="OR = 1 (no association)")

for i, (or_val, p_val) in enumerate(zip(res_df["Odds Ratio"], res_df["Chi2 p-value"])):
    sig = "***" if p_val < 0.001 else "**" if p_val < 0.01 else "*" if p_val < 0.05 else "ns"
    ax.text(or_val, i, f" OR={or_val:.2f} ({sig})", va="center", fontsize=10)

ax.set_xlabel("Odds Ratio")
ax.set_title("Odds of Medication Use: DFU vs No DFU")
ax.legend()
plt.tight_layout()
plt.show()

#Replacing the Nan values; Assuming these features are Missing  At Random
duration_cols = [
    'duration_b_R1_[corticosteroid]_Days',
    'duration_b_R1_[2ndline-antidiabetic]_Days',
    'duration_b_R1_[1stlineantidiabetic]_Days'
]

df[duration_cols] = df[duration_cols].fillna(0)

"""Splitting the Dataset on Patient Level to Prevent Label Leakage"""

import pandas as pd
from sklearn.model_selection import train_test_split

# -----------------------------
# 1. Select the columns you need
# -----------------------------
cols = [
    'Patient_ID',
    'A1c',
    'FBS',
    'duration_b_R1_[corticosteroid]_Days',
    'duration_b_R1_[1stlineantidiabetic]_Days',
    'duration_b_R1_[2ndline-antidiabetic]_Days',
    '[DiabeticFootUlcer)'
]

df_sub = df[cols].copy()

# -----------------------------
# 2. Create patient-level labels
#    A patient is positive if they ever had DFU = 1
# -----------------------------
patient_level = (
    df_sub.groupby('Patient_ID')['[DiabeticFootUlcer)']
    .max()
    .reset_index()
)

# patient_level now has:
# Patient_ID | patient_outcome
# where patient_outcome = 1 if patient ever had positive visit

# -----------------------------
# 3. Split patients, stratified by patient-level outcome
# -----------------------------
train_patients, test_patients = train_test_split(
    patient_level['Patient_ID'],
    test_size=0.2,                      # change if needed
    random_state=42,
    stratify=patient_level['[DiabeticFootUlcer)']
)

# -----------------------------
# 4. Build train/test datasets using patient membership
# -----------------------------
train_df = df_sub[df_sub['Patient_ID'].isin(train_patients)].copy()
test_df  = df_sub[df_sub['Patient_ID'].isin(test_patients)].copy()

# -----------------------------
# 5. Separate X and y
# -----------------------------
target_col = '[DiabeticFootUlcer)'

X_train = train_df.drop(columns=[target_col])
y_train = train_df[target_col]

X_test = test_df.drop(columns=[target_col])
y_test = test_df[target_col]

# -----------------------------
# 6. Check that no patient appears in both sets
# -----------------------------
train_patient_ids = set(train_df['Patient_ID'])
test_patient_ids = set(test_df['Patient_ID'])

overlap = train_patient_ids.intersection(test_patient_ids)
print(f"Number of overlapping patients: {len(overlap)}")

# -----------------------------
# 7. Check class distribution
# -----------------------------
print("\n===== PATIENT-LEVEL DISTRIBUTION =====")
print("Train patients:")
print(patient_level[patient_level['Patient_ID'].isin(train_patients)]['[DiabeticFootUlcer)'].value_counts())

print("\nTest patients:")
print(patient_level[patient_level['Patient_ID'].isin(test_patients)]['[DiabeticFootUlcer)'].value_counts())

print("\n===== VISIT-LEVEL DISTRIBUTION =====")
print(f"Train samples: {len(train_df)}")
print(y_train.value_counts())

print(f"\nTest samples: {len(test_df)}")
print(y_test.value_counts())


print(f"Train size: {X_train.shape[0]} ")
print(f"Test  size: {X_test.shape[0]} ")

print(f"Train DFU count: {y_train.sum()} ({y_train.mean():.3f} prevalence)")
print(f"Test  DFU count: {y_test.sum()} ({y_test.mean():.3f} prevalence)")

"""# CROSS VALIDATION ON LOGISTIC REGRESSION"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# imblearn
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN  # combined over+under




# -----------------------------
# 2) CV setup
# -----------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# -----------------------------
# 3) Shared hyperparameter grid for Logistic Regression
# -----------------------------
param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__penalty": ["l2"],
    "model__solver": ["lbfgs"],
    "model__class_weight": [None, "balanced"],  # you can keep this even with resampling
}

# -----------------------------
# 4) Define the 4 strategies (sampler step differs)
# -----------------------------
strategies = {
    "1_no_resampling": None,

    # Oversampling (simple, fast). You can swap for SMOTE if you prefer.
    "2_oversample_minority": RandomOverSampler(random_state=42),

    # Undersampling majority
    "3_undersample_majority": RandomUnderSampler(random_state=42),

    # Combined: SMOTE (over) + ENN cleaning (under)
    "4_over_and_under_combined": SMOTEENN(random_state=42),
}

results = {}

for name, sampler in strategies.items():
    steps = [
        ("imputer", IterativeImputer(random_state=42)),  # MICE
        ("scaler", StandardScaler()),
    ]

    # only add sampler if strategy uses one
    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", LogisticRegression(max_iter=5000)))

    pipeline = ImbPipeline(steps=steps)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=skf,
        scoring="f1",      # consider 'recall' for DFU if missing positives is costly
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train, y_train)

    # Evaluate on test set once
    best_model = grid.best_estimator_
    y_pred = best_model.predict(X_test)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_score": grid.best_score_,
        "test_report": classification_report(y_test, y_pred, digits=4),
    }

# -----------------------------
# 5) Print results
# -----------------------------
for name, info in results.items():
    print("\n" + "="*70)
    print(f"Strategy: {name}")
    print("Best CV:", info["best_cv_score"])
    print("Best Params:", info["best_params"])
    print("\nTest classification report:\n", info["test_report"])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score
)

# imblearn
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN

# ============================================================
# ASSUMPTION:
# X_train, X_test, y_train, y_test already exist
# and were created using a patient-level split
# ============================================================

# -----------------------------
# 1) CV setup
# -----------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# -----------------------------
# 2) Shared hyperparameter grid
# -----------------------------
param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__penalty": ["l2"],
    "model__solver": ["lbfgs"],
    "model__class_weight": [None, "balanced"],
}

# -----------------------------
# 3) Define strategies
# -----------------------------
strategies = {
    "1_no_resampling": None,
    "2_oversample_minority": RandomOverSampler(random_state=42),
    "3_undersample_majority": RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),
}

results = {}
best_overall_score = -np.inf
best_overall_name = None
best_overall_model = None
best_overall_params = None

# -----------------------------
# 4) Run CV for each strategy
# -----------------------------
for name, sampler in strategies.items():
    steps = [
        ("imputer", IterativeImputer(random_state=42)),
        ("scaler", StandardScaler()),
    ]

    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", LogisticRegression(max_iter=5000)))

    pipeline = ImbPipeline(steps=steps)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=skf,
        scoring="f1",   # can change to "recall" if that matters more
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_
    y_pred = best_model.predict(X_test)

    # For ROC
    y_prob = best_model.predict_proba(X_test)[:, 1]
    auc_score = roc_auc_score(y_test, y_prob)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_score": grid.best_score_,
        "best_model": best_model,
        "test_report": classification_report(y_test, y_pred, digits=4),
        "test_auc": auc_score
    }

    # Track overall best model based on CV performance
    if grid.best_score_ > best_overall_score:
        best_overall_score = grid.best_score_
        best_overall_name = name
        best_overall_model = best_model
        best_overall_params = grid.best_params_

# -----------------------------
# 5) Print all strategy results
# -----------------------------
for name, info in results.items():
    print("\n" + "=" * 70)
    print(f"Strategy: {name}")
    print("Best CV Score:", info["best_cv_score"])
    print("Best Params:", info["best_params"])
    print("Test ROC AUC:", info["test_auc"])
    print("\nTest classification report:\n")
    print(info["test_report"])

# -----------------------------
# 6) Best overall model
# -----------------------------
print("\n" + "=" * 70)
print("BEST OVERALL STRATEGY:", best_overall_name)
print("BEST OVERALL CV SCORE:", best_overall_score)
print("BEST OVERALL PARAMS:", best_overall_params)

# -----------------------------
# 7) Evaluate best overall model on test set
# -----------------------------
y_pred_best = best_overall_model.predict(X_test)
y_prob_best = best_overall_model.predict_proba(X_test)[:, 1]

print("\nFinal Test Classification Report (Best Overall Model):\n")
print(classification_report(y_test, y_pred_best, digits=4))

# -----------------------------
# 8) Confusion Matrix
# -----------------------------
cm = confusion_matrix(y_test, y_pred_best)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format='d')
plt.title(f"Confusion Matrix - {best_overall_name}")
plt.show()

# -----------------------------
# 9) ROC Curve
# -----------------------------
fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
auc_best = roc_auc_score(y_test, y_prob_best)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f"AUC = {auc_best:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve - {best_overall_name}")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, roc_auc_score

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.under_sampling import RandomUnderSampler


# -----------------------------
# 1) Build the BEST pipeline (Strategy 3: undersample)
#    using the BEST params you found
# -----------------------------
best_pipeline = ImbPipeline(steps=[
    ("imputer", IterativeImputer(random_state=42)),       # MICE
    ("scaler", StandardScaler()),                         # scaling
    ("sampler", RandomUnderSampler(random_state=42)),     # Strategy 3 undersampling
    ("model", LogisticRegression(
        C=0.01,
        penalty="l2",
        solver="lbfgs",
        class_weight=None,
        max_iter=5000
    ))
])

# -----------------------------
# 2) Fit on TRAIN, evaluate on TEST
# -----------------------------
best_pipeline.fit(X_train, y_train)

# Predictions (class labels)
y_pred = best_pipeline.predict(X_test)

# Predicted probabilities for ROC/AUC
y_prob = best_pipeline.predict_proba(X_test)[:, 1]


# Predictions (class labels)
y_pred_train = best_pipeline.predict(X_train)

# Predicted probabilities for ROC/AUC
y_prob_train = best_pipeline.predict_proba(X_train)[:, 1]




# -----------------------------
# 3) Confusion Matrix
# -----------------------------
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print("Confusion Matrix:")
print(cm)
print(f"\nTN={tn}, FP={fp}, FN={fn}, TP={tp}")

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format="d")
plt.title("Confusion Matrix (Test Set)")
plt.show()


# -----------------------------
# 4) ROC Curve + AUC
# -----------------------------
auc = roc_auc_score(y_test, y_prob)
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

print(f"\nTest ROC-AUC: {auc:.4f}")

plt.figure()
plt.plot(fpr, tpr, label=f"ROC (AUC = {auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate (FPR)")
plt.ylabel("True Positive Rate (TPR)")
plt.title("ROC Curve (Test Set)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()


# -----------------------------
# 4) ROC Curve + AUC
# -----------------------------
auc = roc_auc_score(y_train, y_prob_train)
fpr, tpr, thresholds = roc_curve(y_train, y_prob_train)

print(f"\nTrain ROC-AUC: {auc:.4f}")

plt.figure()
plt.plot(fpr, tpr, label=f"ROC (AUC = {auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate (FPR)")
plt.ylabel("True Positive Rate (TPR)")
plt.title("ROC Curve (Train Set)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

import statsmodels.api as sm
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, roc_auc_score
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.under_sampling import RandomUnderSampler

# -----------------------------
# 1) Build the BEST pipeline (Strategy 3: undersample)
#    using the BEST params you found
#    (preprocessing only — statsmodels handles the model)
# -----------------------------
best_pipeline = ImbPipeline(steps=[
    ("imputer", IterativeImputer(random_state=42)),       # MICE
    ("scaler", StandardScaler()),                         # scaling
    ("sampler", RandomUnderSampler(random_state=42)),     # Strategy 3 undersampling
])

# -----------------------------
# 2) Fit on TRAIN, evaluate on TEST
# -----------------------------
X_train_processed, y_train_resampled = best_pipeline.fit_resample(X_train, y_train)
X_test_processed = best_pipeline[:-1].transform(X_test)

X_train_processed = pd.DataFrame(X_train_processed, columns=X_train.columns)
X_test_processed = pd.DataFrame(X_test_processed, columns=X_train.columns)

# Add constant for statsmodels intercept
X_train_const = sm.add_constant(X_train_processed)
X_test_const = sm.add_constant(X_test_processed)

# Create and fit logistic regression model
log_reg = sm.Logit(y_train_resampled, X_train_const).fit()

# Get summary report
summary = log_reg.summary()
print(summary)

# =============================================
# TABLE 2: Odds Ratios Summary (exclude Patient_ID and const)
# =============================================
exclude_vars = ['const', 'Patient_ID']
feature_vars = [var for var in coefficients.index if var not in exclude_vars]

table2_rows = []
for var in feature_vars:
    coef = coefficients[var]
    std = original_stds[var]
    OR = odds_ratios[var]
    ci_low = odds_ratios_ci.loc[var, 0]
    ci_up = odds_ratios_ci.loc[var, 1]
    p = p_values[var]

    if p < 0.001:
        sig = "Highly significant"
    elif p < 0.05:
        sig = "Significant"
    elif p < 0.10:
        sig = "Borderline"
    else:
        sig = "Not significant"

    table2_rows.append({
        'Variable': var,
        'Coefficient': round(coef, 4),
        'Original SD': round(std, 2),
        'Odds Ratio': round(OR, 4),
        '95% CI': f"{ci_low:.4f} – {ci_up:.4f}",
        'P-value': f"{p:.4f}" if p >= 0.001 else "<0.001",
        'Significance': sig
    })

table2 = pd.DataFrame(table2_rows).set_index('Variable')

print("\n===== Table 2: Odds Ratios Summary =====")
print(table2.to_string())

# =============================================
# TABLE 3: Clinical Interpretation (ALL variables)
# =============================================
table3_rows = []
for var in feature_vars:
    coef = coefficients[var]
    std = original_stds[var]
    OR = odds_ratios[var]

    # Direction and % change per 1 SD
    if coef > 0:
        direction = "Increases"
        pct_sd = (OR - 1) * 100
    else:
        direction = "Decreases"
        pct_sd = (1 - OR) * 100

    # Per-year / per-unit calculation
    coef_per_unit = coef / std  # coefficient in original units

    if 'Days' in var or 'days' in var:
        coef_per_year = coef_per_unit * 365
        OR_per_year = np.exp(coef_per_year)
        pct_year = (OR_per_year - 1) * 100 if coef > 0 else -(1 - OR_per_year) * 100
        unit_label = "365 days"
    else:
        OR_per_year = np.exp(coef_per_unit)  # per 1 original unit
        pct_year = (OR_per_year - 1) * 100 if coef > 0 else -(1 - OR_per_year) * 100
        unit_label = "1 original unit"

    table3_rows.append({
        'Variable': var,
        'Direction': direction,
        '% Change per 1 SD': f"{pct_sd:.1f}%",
        'Per-Unit Label': unit_label,
        'OR per Unit': round(OR_per_year, 4),
        '% Change per Unit': f"{pct_year:.1f}%"
    })

table3 = pd.DataFrame(table3_rows).set_index('Variable')

print("\n===== Table 3: Clinical Interpretation =====")
print(table3.to_string())

# -----------------------------
# Predictions
# -----------------------------
# Predictions (class labels)
y_pred = (log_reg.predict(X_test_const) >= 0.5).astype(int)
# Predicted probabilities for ROC/AUC
y_prob = log_reg.predict(X_test_const)

# Predictions (class labels)
y_pred_train = (log_reg.predict(X_train_const) >= 0.5).astype(int)
# Predicted probabilities for ROC/AUC
y_prob_train = log_reg.predict(X_train_const)

"""NEW CODE

# GAUSSIAN NAIVE BAYES
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN


# =========================================================
# Assumes you already have:
# X_train, X_test, y_train, y_test from train_test_split(...)
# =========================================================


# -----------------------------
# CV setup
# -----------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# -----------------------------
# GaussianNB hyperparameter grid
# -----------------------------
# var_smoothing adds a small value to variances for numerical stability.
# Tuning it can materially affect performance on some datasets.
param_grid = {
    "model__var_smoothing": np.logspace(-12, -6, 13)  # 1e-12 ... 1e-6
}

# -----------------------------
# Strategies (samplers)
# -----------------------------
strategies = {
    "1_no_resampling": None,
    "2_oversample_minority": RandomOverSampler(random_state=42),  # or SMOTE(random_state=42)
    "3_undersample_majority": RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),       # combined
}

results = {}

# -----------------------------
# Run GridSearch for each strategy
# -----------------------------
for name, sampler in strategies.items():
    steps = [
        ("imputer", IterativeImputer(random_state=42)),
        # GaussianNB usually doesn't need scaling; keep pipeline simple.
        # If you want scaling, add: ("scaler", StandardScaler()),
    ]

    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", GaussianNB()))

    pipeline = ImbPipeline(steps=steps)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=skf,
        scoring="f1",   # for extreme imbalance, consider "average_precision" too
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    # ---- Test predictions
    y_pred = best_model.predict(X_test)

    # GaussianNB supports predict_proba -> use for ROC/AUC
    y_prob = best_model.predict_proba(X_test)[:, 1]

    # ---- Metrics
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    auc = roc_auc_score(y_test, y_prob)
    fpr, tpr, _ = roc_curve(y_test, y_prob)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_f1": grid.best_score_,
        "confusion_matrix": cm,
        "tn_fp_fn_tp": (tn, fp, fn, tp),
        "test_report": classification_report(y_test, y_pred, digits=4),
        "auc": auc,
        "roc": (fpr, tpr),
    }

# -----------------------------
# Print + Plot
# -----------------------------
for name, info in results.items():
    print("\n" + "=" * 75)
    print(f"Strategy: {name}")
    print(f"Best CV F1: {info['best_cv_f1']}")
    print(f"Best Params: {info['best_params']}")

    cm = info["confusion_matrix"]
    tn, fp, fn, tp = info["tn_fp_fn_tp"]
    print("\nConfusion Matrix:")
    print(cm)
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

    print("\nTest classification report:\n")
    print(info["test_report"])

    print(f"Test ROC-AUC: {info['auc']:.4f}")

    fpr, tpr = info["roc"]
    plt.figure()
    plt.plot(fpr, tpr, label=f"{name} (AUC={info['auc']:.4f})")
    plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
    plt.xlabel("False Positive Rate (FPR)")
    plt.ylabel("True Positive Rate (TPR)")
    plt.title(f"ROC Curve - {name}")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.combine import SMOTEENN


# ============================================
# Best model from CV (Strategy 4)
# ============================================
final_model = ImbPipeline(steps=[
    ("imputer", IterativeImputer(random_state=42)),
    ("sampler", SMOTEENN(random_state=42)),
    ("model", GaussianNB(var_smoothing=1e-6))
])


# ============================================
# Fit on TRAIN
# ============================================
final_model.fit(X_train, y_train)


# ============================================
# Function to evaluate split
# ============================================
def evaluate_split(name, X, y, model):

    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    cm = confusion_matrix(y, y_pred)
    tn, fp, fn, tp = cm.ravel()

    auc = roc_auc_score(y, y_prob)

    print("\n" + "="*70)
    print(f"{name} RESULTS")
    print("="*70)
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")
    print(f"ROC-AUC: {auc:.4f}\n")
    print(classification_report(y, y_pred, digits=4))

    # Plot confusion matrix
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(values_format="d")
    plt.title(f"{name} Confusion Matrix")
    plt.show()

    return auc


# ============================================
# Evaluate TRAIN and TEST
# ============================================
auc_train = evaluate_split("TRAIN", X_train, y_train, final_model)
auc_test  = evaluate_split("TEST",  X_test,  y_test,  final_model)


# ============================================
# Compare ROC Curves
# ============================================
y_prob_train = final_model.predict_proba(X_train)[:,1]
y_prob_test  = final_model.predict_proba(X_test)[:,1]

fpr_tr, tpr_tr, _ = roc_curve(y_train, y_prob_train)
fpr_te, tpr_te, _ = roc_curve(y_test, y_prob_test)

plt.figure()
plt.plot(fpr_tr, tpr_tr, label=f"Train ROC (AUC={auc_train:.4f})")
plt.plot(fpr_te, tpr_te, label=f"Test ROC (AUC={auc_test:.4f})")
plt.plot([0,1], [0,1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison (Train vs Test)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""PREDICTION"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, roc_auc_score, classification_report

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.combine import SMOTEENN


# ---------------------------------------------------
# Best settings from your CV results:
# Strategy 4_over_and_under_combined
# var_smoothing = 1e-6
# ---------------------------------------------------
best_model = ImbPipeline(steps=[
    ("imputer", IterativeImputer(random_state=42)),
    ("sampler", SMOTEENN(random_state=42)),
    ("model", GaussianNB(var_smoothing=1e-6))
])

# 1) Fit ONLY on training data
best_model.fit(X_train, y_train)

# 2) Predict on UNSEEN test data
y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]  # for ROC/AUC


# ---------------------------------------------------
# Confusion Matrix
# ---------------------------------------------------
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

print("Confusion Matrix (Test):")
print(cm)
print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format="d")
plt.title("Confusion Matrix (GaussianNB Best Params) - Test Set")
plt.show()


# ---------------------------------------------------
# Classification report
# ---------------------------------------------------
print("\nClassification Report (Test):\n")
print(classification_report(y_test, y_pred, digits=4))


# ---------------------------------------------------
# ROC Curve + AUC
# ---------------------------------------------------
auc = roc_auc_score(y_test, y_prob)
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

print(f"\nTest ROC-AUC: {auc:.4f}")

plt.figure()
plt.plot(fpr, tpr, label=f"ROC Curve (AUC = {auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate (FPR)")
plt.ylabel("True Positive Rate (TPR)")
plt.title("ROC Curve (GaussianNB Best Params) - Test Set")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import GridSearchCV, StratifiedGroupKFold, cross_val_predict
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN


# =========================================================
# ASSUMES you already have from your patient-level split:
# X_train, X_test, y_train, y_test
# where X_train and X_test still contain 'Patient_ID'
# =========================================================

target_col = '[DiabeticFootUlcer)'
group_col = 'Patient_ID'

# ---------------------------------------------------------
# Remove Patient_ID from model inputs, but keep it for grouping
# ---------------------------------------------------------
X_train_model = X_train.drop(columns=[group_col]).copy()
X_test_model  = X_test.drop(columns=[group_col]).copy()

train_groups = X_train[group_col].copy()
test_groups  = X_test[group_col].copy()

# ---------------------------------------------------------
# Sanity check: no patient leakage between train and test
# ---------------------------------------------------------
overlap = set(train_groups).intersection(set(test_groups))
print(f"Number of overlapping patients between train and test: {len(overlap)}")

# ---------------------------------------------------------
# Grouped CV
# ---------------------------------------------------------
cv = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

# ---------------------------------------------------------
# Hyperparameter grid for GaussianNB
# ---------------------------------------------------------
param_grid = {
    "model__var_smoothing": np.logspace(-12, -6, 13)
}

# ---------------------------------------------------------
# Sampling strategies
# ---------------------------------------------------------
strategies = {
    "1_no_resampling": None,
    "2_oversample_minority": RandomOverSampler(random_state=42),
    "3_undersample_majority": RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),
}

# ---------------------------------------------------------
# Threshold search function
# ---------------------------------------------------------
def find_best_threshold(y_true, y_prob, thresholds=None, metric="f1"):
    """
    Find the best probability threshold based on chosen metric.
    metric can be: 'f1', 'recall', 'precision'
    """
    if thresholds is None:
        thresholds = np.arange(0.05, 0.96, 0.01)

    best_threshold = 0.5
    best_score = -1
    history = []

    for thr in thresholds:
        y_pred_thr = (y_prob >= thr).astype(int)

        if metric == "f1":
            score = f1_score(y_true, y_pred_thr, zero_division=0)
        elif metric == "recall":
            score = recall_score(y_true, y_pred_thr, zero_division=0)
        elif metric == "precision":
            score = precision_score(y_true, y_pred_thr, zero_division=0)
        else:
            raise ValueError("metric must be one of: 'f1', 'recall', 'precision'")

        prec = precision_score(y_true, y_pred_thr, zero_division=0)
        rec = recall_score(y_true, y_pred_thr, zero_division=0)
        f1 = f1_score(y_true, y_pred_thr, zero_division=0)

        history.append({
            "threshold": thr,
            "precision": prec,
            "recall": rec,
            "f1": f1,
            "score_used_for_selection": score
        })

        if score > best_score:
            best_score = score
            best_threshold = thr

    return best_threshold, best_score, history


results = {}

best_overall_cv_score = -np.inf
best_overall_name = None
best_overall_model = None
best_overall_threshold = None
best_overall_test_auc = None

# ---------------------------------------------------------
# Run grouped CV + hyperparameter tuning + threshold tuning
# ---------------------------------------------------------
for name, sampler in strategies.items():
    print("\n" + "=" * 80)
    print(f"Running strategy: {name}")

    steps = [
        ("imputer", IterativeImputer(random_state=42)),
    ]

    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", GaussianNB()))

    pipeline = ImbPipeline(steps=steps)

    # ---------------------------------------------
    # Step 1: Hyperparameter tuning on training set
    # ---------------------------------------------
    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=cv,
        scoring="f1",   # can change to "recall" or "average_precision"
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train_model, y_train, groups=train_groups)
    best_model = grid.best_estimator_

    # ---------------------------------------------
    # Step 2: Get out-of-fold probabilities on train
    #         for threshold tuning only on train data
    # ---------------------------------------------
    train_oof_prob = cross_val_predict(
        best_model,
        X_train_model,
        y_train,
        groups=train_groups,
        cv=cv,
        method="predict_proba",
        n_jobs=-1
    )[:, 1]

    # Choose threshold based on CV probabilities from training set
    best_threshold, best_threshold_score, threshold_history = find_best_threshold(
        y_true=y_train,
        y_prob=train_oof_prob,
        thresholds=np.arange(0.05, 0.96, 0.01),
        metric="f1"   # choose threshold that maximizes F1 on train CV preds
    )

    # ---------------------------------------------
    # Step 3: Fit best model on full training set
    # ---------------------------------------------
    best_model.fit(X_train_model, y_train)

    # ---------------------------------------------
    # Step 4: Evaluate on test set using tuned threshold
    # ---------------------------------------------
    y_prob_test = best_model.predict_proba(X_test_model)[:, 1]
    y_pred_test = (y_prob_test >= best_threshold).astype(int)

    cm = confusion_matrix(y_test, y_pred_test)
    tn, fp, fn, tp = cm.ravel()

    test_auc = roc_auc_score(y_test, y_prob_test)
    fpr, tpr, roc_thresholds = roc_curve(y_test, y_prob_test)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_f1": grid.best_score_,
        "best_model": best_model,
        "best_threshold": best_threshold,
        "best_threshold_score": best_threshold_score,
        "threshold_history": threshold_history,
        "confusion_matrix": cm,
        "tn_fp_fn_tp": (tn, fp, fn, tp),
        "test_report": classification_report(y_test, y_pred_test, digits=4, zero_division=0),
        "test_auc": test_auc,
        "roc": (fpr, tpr, roc_thresholds),
        "y_prob_test": y_prob_test,
        "y_pred_test": y_pred_test,
        "train_oof_prob": train_oof_prob,
    }

    # Track overall best strategy by CV F1
    if grid.best_score_ > best_overall_cv_score:
        best_overall_cv_score = grid.best_score_
        best_overall_name = name
        best_overall_model = best_model
        best_overall_threshold = best_threshold
        best_overall_test_auc = test_auc


# ---------------------------------------------------------
# Print results
# ---------------------------------------------------------
for name, info in results.items():
    print("\n" + "=" * 80)
    print(f"Strategy: {name}")
    print(f"Best CV F1: {info['best_cv_f1']:.6f}")
    print(f"Best Params: {info['best_params']}")
    print(f"Best Threshold: {info['best_threshold']:.2f}")
    print(f"Threshold-selection score (train CV F1): {info['best_threshold_score']:.6f}")

    tn, fp, fn, tp = info["tn_fp_fn_tp"]
    print("\nConfusion Matrix:")
    print(info["confusion_matrix"])
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

    print("\nTest classification report:\n")
    print(info["test_report"])

    print(f"Test ROC-AUC: {info['test_auc']:.4f}")


# ---------------------------------------------------------
# Plot ROC curves for all strategies
# ---------------------------------------------------------
plt.figure(figsize=(8, 6))
for name, info in results.items():
    fpr, tpr, _ = info["roc"]
    plt.plot(fpr, tpr, label=f"{name} (AUC={info['test_auc']:.4f})")

plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curves - GaussianNB Strategies")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()


# ---------------------------------------------------------
# Best overall strategy
# ---------------------------------------------------------
print("\n" + "=" * 80)
print(f"BEST OVERALL STRATEGY: {best_overall_name}")
print(f"BEST OVERALL CV F1: {best_overall_cv_score:.6f}")
print(f"BEST OVERALL THRESHOLD: {best_overall_threshold:.2f}")
print(f"BEST OVERALL TEST AUC: {best_overall_test_auc:.4f}")

best_info = results[best_overall_name]

# ---------------------------------------------------------
# Final confusion matrix plot for best strategy
# ---------------------------------------------------------
disp = ConfusionMatrixDisplay(confusion_matrix=best_info["confusion_matrix"])
disp.plot(values_format='d')
plt.title(f"Confusion Matrix - {best_overall_name}\nThreshold = {best_info['best_threshold']:.2f}")
plt.show()


# ---------------------------------------------------------
# Final ROC curve for best strategy
# ---------------------------------------------------------
fpr_best, tpr_best, _ = best_info["roc"]
plt.figure(figsize=(7, 5))
plt.plot(fpr_best, tpr_best, label=f"AUC = {best_info['test_auc']:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve - {best_overall_name}")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()


# ---------------------------------------------------------
# Plot threshold tuning curves for best strategy
# ---------------------------------------------------------
hist = best_info["threshold_history"]
thr_vals = [d["threshold"] for d in hist]
prec_vals = [d["precision"] for d in hist]
rec_vals  = [d["recall"] for d in hist]
f1_vals   = [d["f1"] for d in hist]

plt.figure(figsize=(8, 5))
plt.plot(thr_vals, prec_vals, label="Precision")
plt.plot(thr_vals, rec_vals, label="Recall")
plt.plot(thr_vals, f1_vals, label="F1")
plt.axvline(best_info["best_threshold"], linestyle="--", label=f"Best threshold = {best_info['best_threshold']:.2f}")
plt.xlabel("Threshold")
plt.ylabel("Score")
plt.title(f"Threshold Tuning on Training CV Predictions - {best_overall_name}")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()


# ---------------------------------------------------------
# Optional: Precision-Recall curve on the test set
# ---------------------------------------------------------
precision_test, recall_test, pr_thresholds = precision_recall_curve(y_test, best_info["y_prob_test"])

plt.figure(figsize=(7, 5))
plt.plot(recall_test, precision_test)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title(f"Precision-Recall Curve - {best_overall_name}")
plt.grid(True, alpha=0.3)
plt.show()

"""# XGBOOST"""

# Standard library
import numpy as np
import matplotlib.pyplot as plt

# sklearn preprocessing & pipeline
from sklearn.experimental import enable_iterative_imputer   # noqa: F401
from sklearn.impute import IterativeImputer, SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# sklearn model selection & metrics
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    GridSearchCV,
)
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
    confusion_matrix,
    ConfusionMatrixDisplay,
    classification_report,
)

# Gradient boosting
from sklearn.ensemble import GradientBoostingClassifier

# imbalanced-learn (mirrors GaussianNB section style)
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN

x_cont = X_train.columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', Pipeline([
            ('imputer', IterativeImputer(random_state=42)),
        ]), x_cont),
    ],
    remainder='drop',    # Explicitly drop any columns not handled by transformers
)

# Resampling strategies
strategies = {
    "1_no_resampling":          None,
    "2_oversample_minority":    RandomOverSampler(random_state=42),
    "3_undersample_majority":   RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),
}

# Hyperparameter grid for GradientBoostingClassifier


param_grid = {
    "xg_boost__n_estimators": [25, 50, 100],
    "xg_boost__max_depth":[1, 3, 5, 7],
    "xg_boost__learning_rate":[0.05,0.1],
    "xg_boost__min_samples_leaf":[1, 5, 10], # sklearn analog to min_child_weight
}
# CV setup — 5 folds as used throughout the project
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

#  Grid search across all four resampling strategies
xgb_results = {}

for name, sampler in strategies.items():

    # Build pipeline steps dynamically (mirrors Logistic Regression section)
    steps = [("preprocessor", preprocessor)]

    if sampler is not None:
        # Special handling for SMOTEENN to adjust k_neighbors if necessary
        if isinstance(sampler, SMOTEENN):
            steps.append(("sampler", SMOTEENN(random_state=42, smote=SMOTE(k_neighbors=3, random_state=42))))
        else:
            steps.append(("sampler", sampler))

    steps.append(("xg_boost", GradientBoostingClassifier(random_state=42)))

    # Use ImbPipeline so resamplers work correctly inside cross-validation
    model = ImbPipeline(steps=steps)

    # Grid search
    grid = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        cv=skf,
        scoring='recall',       # Prioritising recall: missing a DFU case is costly
        n_jobs=-1,
        verbose=0,
        refit=True,
    )

    grid.fit(X_train, y_train)

    # ── Predictions ──────────────────────────────────────────────────────
    best_model = grid.best_estimator_
    y_pred     = best_model.predict(X_test)
    y_prob     = best_model.predict_proba(X_test)[:, 1]

    # ── Metrics ──────────────────────────────────────────────────────────
    cm         = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    auc        = roc_auc_score(y_test, y_prob)
    fpr, tpr, _ = roc_curve(y_test, y_prob)

    xgb_results[name] = {
        "best_params":   grid.best_params_,
        "best_cv_recall": grid.best_score_,
        "confusion_matrix": cm,
        "tn_fp_fn_tp":   (tn, fp, fn, tp),
        "test_report":   classification_report(y_test, y_pred, digits=4),
        "auc":           auc,
        "roc":           (fpr, tpr),
        "best_estimator": best_model,
    }



# =========================================================
# Print results
# =========================================================
for name, info in xgb_results.items():
    print("\n" + "=" * 75)
    print(f"Strategy: {name}")
    print(f"Best CV Recall : {info['best_cv_recall']:.4f}")
    print(f"Best Params    : {info['best_params']}")

    tn, fp, fn, tp = info['tn_fp_fn_tp']
    print("\nConfusion Matrix:")
    print(info['confusion_matrix'])
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

    print("\nTest Classification Report:")
    print(info['test_report'])
    print(f"Test ROC-AUC: {info['auc']:.4f}")

    # ROC curve plot
    fpr, tpr = info['roc']
    plt.figure()
    plt.plot(fpr, tpr, label=f"{name} (AUC={info['auc']:.4f})")
    plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
    plt.xlabel("False Positive Rate (FPR)")
    plt.ylabel("True Positive Rate (TPR)")
    plt.title(f"ROC Curve – XGBoost – {name}")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

# =========================================================
# Best model: final evaluation
# =========================================================
# Select the strategy with the highest test AUC for final reporting.
best_strategy = max(xgb_results, key=lambda k: xgb_results[k]['auc'])
print(f"\n>>> Best overall strategy: {best_strategy}")

final_parameters = xgb_results[best_strategy]['best_params']
print(f"Best parameters: {final_parameters}")

final_model = xgb_results[best_strategy]['best_estimator']


def evaluate_split_xgb(name: str, X, y, model) -> float:
    """
    Compute and display full metrics for a given split.
    Mirrors the evaluate_split() helper from the GaussianNB section.
    """
    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    cm          = confusion_matrix(y, y_pred)
    tn, fp, fn, tp = cm.ravel()
    auc_score   = roc_auc_score(y, y_prob)

    print("\n" + "=" * 70)
    print(f"{name} RESULTS  (XGBoost – {best_strategy})")
    print("=" * 70)
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")
    print(f"ROC-AUC : {auc_score:.4f}\n")
    print(classification_report(y, y_pred, digits=4))

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(values_format="d")
    plt.title(f"{name} Confusion Matrix – XGBoost")
    plt.show()

    return auc_score



# ============================================
# Evaluate TRAIN and TEST
# ============================================
auc_train = evaluate_split_xgb("TRAIN", X_train, y_train, final_model)
auc_test  = evaluate_split_xgb("TEST",  X_test,  y_test,  final_model)



# ============================================
# Compare ROC Curves
# ============================================
y_prob_train = final_model.predict_proba(X_train)[:,1]
y_prob_test  = final_model.predict_proba(X_test)[:,1]

fpr_tr, tpr_tr, _ = roc_curve(y_train, y_prob_train)
fpr_te, tpr_te, _ = roc_curve(y_test, y_prob_test)

plt.figure()
plt.plot(fpr_tr, tpr_tr, label=f"Train ROC (AUC={auc_train:.4f})")
plt.plot(fpr_te, tpr_te, label=f"Test ROC (AUC={auc_test:.4f})")
plt.plot([0,1], [0,1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison (Train vs Test)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()