# -*- coding: utf-8 -*-
"""Project HAD5016H

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXF7ZgIpLjGV7JmdxSyCUG5NFOyNTD5N
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, accuracy_score
import warnings
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import TargetEncoder
#from category_encoders import TargetEncoder
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import StandardScaler
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.metrics import RocCurveDisplay, auc, roc_curve

#Validation section of tutorial
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold

warnings.filterwarnings('ignore')

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv("drive/My Drive/Colab Notebooks/TMU_DM_808K_R1.csv") #Add your file path here

data.head()

#Checking if there are duplicates in Patients (a patient appears more than once)
data['Patient_ID'].is_unique

data['Patient_ID'].nunique()

"""There are 171619 patients with some patients having more than one visit"""

data.columns

#Descriptive Statistics for the Dataset
data.describe()

"""Finding the number of patients with or without diabetes"""

data['Diabetes'].value_counts()

#Subsetting the dataset to contain only patients with Diabetes
data = data[data['Diabetes'] == 1]

#Confirming if the subsetting has been done (Datasets for patients diabetes only)
data['Diabetes'].value_counts()

#Filtering out our interested features and label (DiabeticFootUlcer) into a new dataframe, df
df = data[['Patient_ID','Sex','A1c','FBS', 'duration_b_R1_[corticosteroid]_Days', 'duration_b_R1_[1stlineantidiabetic]_Days', 'duration_b_R1_[2ndline-antidiabetic]_Days'  ,'[DiabeticFootUlcer)']]
df = df.reset_index(drop=True)
df.head()

#Numerical Statistics of the dataset, df
df.describe()

#Checking for the null values in the dataset
df.isna().sum()

#Dropping the rows with null values in the Label since they cannot be determined
df.dropna(subset = ["[DiabeticFootUlcer)"], inplace=True)
df.head()

#A pie chart demonstrating class imbalance in the dataset
counts = df['[DiabeticFootUlcer)'].value_counts()

# Define colors
colors = ['#1c3a73', '#7cb1c2']

# Create pie chart
plt.figure(figsize=(6, 6)) #tuple for fig size, 6x6 inches
plt.pie(
    counts, #counts for each class
    labels=[f'{cls} ({count})' for cls, count in counts.items()],  # add labels with counts... counts.items() returns an iterable of tuples
                                                                    #e.g., [('class', count)], which are then unpacked and formatted into labels
    autopct='%1.1f%%',  # Show percentages
    colors=colors,
    startangle=90
)

# Set title
plt.title('Distribution of DiabeticFootUlcer', fontsize=14)

# Show plot
plt.show()

#Resetting the index
df = df.reset_index(drop=True)
df.head()

# Using the map() function to transform the 'Sex' column
df['Sex'] = df['Sex'].map({'Male': 0, 'Female': 1})
df

df['[DiabeticFootUlcer)'] = df['[DiabeticFootUlcer)'].astype(int)
df.dtypes

print(df.shape)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# 0) Make sure target is clean
# -----------------------------
df = df.copy()

target_col = "[DiabeticFootUlcer)"
unneeded_cols = ["Patient_ID"]

num_cols = [c for c in df.columns if c not in [target_col] + unneeded_cols]



# -----------------------------
# 1) Basic overview
# -----------------------------
print("Shape:", df.shape)
print("\nDtypes:\n", df.dtypes)
print("\nMissing values count:\n", df.isna().sum())
print("\nMissing values (%):\n", (df.isna().mean() * 100).round(2))

print("\nTarget distribution:")
print(df[target_col].value_counts(dropna=False))
print("\nTarget distribution (%):")
print((df[target_col].value_counts(dropna=False, normalize=True) * 100).round(2))

print("\nSummary stats (numeric):")
print(df[num_cols].describe().T)

# -----------------------------
# 2) Missingness bar plot
# -----------------------------
missing_pct = (df.isna().mean() * 100).sort_values(ascending=False)
missing_pct = missing_pct[missing_pct > 0]

if len(missing_pct) > 0:
    plt.figure()
    missing_pct.plot(kind="bar")
    plt.title("Missing Values (%) by Column")
    plt.ylabel("Percent Missing")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()
else:
    print("\n✅ No missing values found in these columns.")

# -----------------------------
# 3) Distributions + Outliers (Boxplots)
# -----------------------------
# Histograms
for col in num_cols:
    plt.figure()
    x = df[col].dropna()
    plt.hist(x, bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.tight_layout()
    plt.show()

# Boxplots (outlier view)
for col in num_cols:
    plt.figure()
    x = df[col].dropna()
    plt.boxplot(x, vert=True)
    plt.title(f"Boxplot (Outliers) of {col}")
    plt.ylabel(col)
    plt.tight_layout()
    plt.show()

# -----------------------------
# 4) Outlier counts using IQR rule (numeric report)
# -----------------------------
def iqr_outlier_count(series: pd.Series):
    s = series.dropna()
    if len(s) < 4:
        return 0, np.nan, np.nan
    q1 = s.quantile(0.25)
    q3 = s.quantile(0.75)
    iqr = q3 - q1
    lo = q1 - 1.5 * iqr
    hi = q3 + 1.5 * iqr
    outliers = ((s < lo) | (s > hi)).sum()
    return int(outliers), lo, hi

print("\nIQR-based outlier summary:")
for col in num_cols:
    out_ct, lo, hi = iqr_outlier_count(df[col])
    print(f"{col}: outliers={out_ct}, IQR-bounds=({lo:.3g}, {hi:.3g})")

# -----------------------------
# 5) DFU vs non-DFU comparison (Boxplots by class)
# -----------------------------
# (only if target has both classes)
if df[target_col].nunique(dropna=True) >= 2:
    for col in num_cols:
        plt.figure()
        # Prepare group arrays
        g0 = df.loc[df[target_col] == 0, col].dropna()
        g1 = df.loc[df[target_col] == 1, col].dropna()
        plt.boxplot([g0, g1], labels=["No DFU", "DFU"])
        plt.title(f"{col} by DFU status")
        plt.ylabel(col)
        plt.tight_layout()
        plt.show()

# -----------------------------
# 6) Collinearity: Correlation matrix + Heatmap
# -----------------------------
corr = df[num_cols].corr()

plt.figure()
plt.imshow(corr, aspect="auto")
plt.title("Correlation Heatmap (Numeric Features)")
plt.xticks(range(len(num_cols)), num_cols, rotation=45, ha="right")
plt.yticks(range(len(num_cols)), num_cols)
plt.colorbar()
plt.tight_layout()
plt.show()

print("\nCorrelation matrix:")
print(corr.round(3))

# Show highly correlated pairs
threshold = 0.8
high_pairs = []
cols = corr.columns
for i in range(len(cols)):
    for j in range(i+1, len(cols)):
        val = corr.iloc[i, j]
        if abs(val) >= threshold:
            high_pairs.append((cols[i], cols[j], val))

if high_pairs:
    print(f"\nHighly correlated pairs (|r| >= {threshold}):")
    for a, b, v in sorted(high_pairs, key=lambda x: abs(x[2]), reverse=True):
        print(f"{a} vs {b}: r={v:.3f}")
else:
    print(f"\n✅ No feature pairs with |r| >= {threshold} in this subset.")

# -----------------------------
# 7) Quick pairwise scatter plots (small subset only)
# -----------------------------
# Helpful to visually see relationships (and weird clusters)
for i in range(len(num_cols)):
    for j in range(i+1, len(num_cols)):
        xcol, ycol = num_cols[i], num_cols[j]
        plt.figure()
        x = df[xcol]
        y = df[ycol]
        plt.scatter(x, y)
        plt.title(f"Scatter: {xcol} vs {ycol}")
        plt.xlabel(xcol)
        plt.ylabel(ycol)
        plt.tight_layout()
        plt.show()

# Correlation matrix to quantify relationships
corr_data = df[['A1c','FBS', 'duration_b_R1_[corticosteroid]_Days', 'duration_b_R1_[1stlineantidiabetic]_Days', 'duration_b_R1_[2ndline-antidiabetic]_Days'  ,'[DiabeticFootUlcer)']]
corr_matrix = corr_data.corr()
sns.heatmap(corr_matrix, annot=True, fmt=".2f")

#Replacing the Nan values; Assuming these features are Missing  At Random
duration_cols = [
    'duration_b_R1_[corticosteroid]_Days',
    'duration_b_R1_[2ndline-antidiabetic]_Days',
    'duration_b_R1_[1stlineantidiabetic]_Days'
]

df[duration_cols] = df[duration_cols].fillna(0)

"""Splitting the Dataset on Patient Level to Prevent Label Leakage"""

import pandas as pd
from sklearn.model_selection import train_test_split

# -----------------------------
# 1. Select the columns you need
# -----------------------------
cols = [
    'Patient_ID',
    'A1c',
    'FBS',
    'duration_b_R1_[corticosteroid]_Days',
    'duration_b_R1_[1stlineantidiabetic]_Days',
    'duration_b_R1_[2ndline-antidiabetic]_Days',
    '[DiabeticFootUlcer)'
]

df_sub = df[cols].copy()

# -----------------------------
# 2. Create patient-level labels
#    A patient is positive if they ever had DFU = 1
# -----------------------------
patient_level = (
    df_sub.groupby('Patient_ID')['[DiabeticFootUlcer)']
    .max()
    .reset_index()
)

# patient_level now has:
# Patient_ID | patient_outcome
# where patient_outcome = 1 if patient ever had positive visit

# -----------------------------
# 3. Split patients, stratified by patient-level outcome
# -----------------------------
train_patients, test_patients = train_test_split(
    patient_level['Patient_ID'],
    test_size=0.2,                      # change if needed
    random_state=42,
    stratify=patient_level['[DiabeticFootUlcer)']
)

# -----------------------------
# 4. Build train/test datasets using patient membership
# -----------------------------
train_df = df_sub[df_sub['Patient_ID'].isin(train_patients)].copy()
test_df  = df_sub[df_sub['Patient_ID'].isin(test_patients)].copy()

# -----------------------------
# 5. Separate X and y
# -----------------------------
target_col = '[DiabeticFootUlcer)'

X_train = train_df.drop(columns=[target_col])
y_train = train_df[target_col]

X_test = test_df.drop(columns=[target_col])
y_test = test_df[target_col]

# -----------------------------
# 6. Check that no patient appears in both sets
# -----------------------------
train_patient_ids = set(train_df['Patient_ID'])
test_patient_ids = set(test_df['Patient_ID'])

overlap = train_patient_ids.intersection(test_patient_ids)
print(f"Number of overlapping patients: {len(overlap)}")

# -----------------------------
# 7. Check class distribution
# -----------------------------
print("\n===== PATIENT-LEVEL DISTRIBUTION =====")
print("Train patients:")
print(patient_level[patient_level['Patient_ID'].isin(train_patients)]['[DiabeticFootUlcer)'].value_counts())

print("\nTest patients:")
print(patient_level[patient_level['Patient_ID'].isin(test_patients)]['[DiabeticFootUlcer)'].value_counts())

print("\n===== VISIT-LEVEL DISTRIBUTION =====")
print(f"Train samples: {len(train_df)}")
print(y_train.value_counts())

print(f"\nTest samples: {len(test_df)}")
print(y_test.value_counts())

"""## CROSS VALIDATION ON LOGISTIC REGRESSION

# New Section
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    roc_auc_score
)

# imblearn
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN



# -----------------------------
# 1) CV setup
# -----------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# -----------------------------
# 2) Shared hyperparameter grid
# -----------------------------
param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__penalty": ["l2"],
    "model__solver": ["lbfgs"],
    "model__class_weight": [None, "balanced"],
}


# 3) Define strategies
strategies = {
    "1_no_resampling": None,
    "2_oversample_minority": RandomOverSampler(random_state=42),
    "3_undersample_majority": RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),
}

results = {}
best_overall_score = -np.inf
best_overall_name = None
best_overall_model = None
best_overall_params = None


# 4) Run CV for each strategy
for name, sampler in strategies.items():
    steps = [
        ("imputer", IterativeImputer(random_state=42)),
        ("scaler", StandardScaler()),
    ]

    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", LogisticRegression(max_iter=5000)))

    pipeline = ImbPipeline(steps=steps)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=skf,
        scoring="f1",   # can change to "recall" if that matters more
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_
    y_pred = best_model.predict(X_test)

    # For ROC
    y_prob = best_model.predict_proba(X_test)[:, 1]
    auc_score = roc_auc_score(y_test, y_prob)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_score": grid.best_score_,
        "best_model": best_model,
        "test_report": classification_report(y_test, y_pred, digits=4),
        "test_auc": auc_score
    }

    # Track overall best model based on CV performance
    if grid.best_score_ > best_overall_score:
        best_overall_score = grid.best_score_
        best_overall_name = name
        best_overall_model = best_model
        best_overall_params = grid.best_params_


# 5) Print all strategy results
for name, info in results.items():
    print("\n" + "=" * 70)
    print(f"Strategy: {name}")
    print("Best CV Score:", info["best_cv_score"])
    print("Best Params:", info["best_params"])
    print("Test ROC AUC:", info["test_auc"])
    print("\nTest classification report:\n")
    print(info["test_report"])


# 6) Best overall model
print("\n" + "=" * 70)
print("BEST OVERALL STRATEGY:", best_overall_name)
print("BEST OVERALL CV SCORE:", best_overall_score)
print("BEST OVERALL PARAMS:", best_overall_params)


# 7) Evaluate best overall model on Train set to check for overfitting
ytrain_pred_best = best_overall_model.predict(X_train)
ytrain_prob_best = best_overall_model.predict_proba(X_train)[:, 1]

print("\nFinal Test Classification Report (Best Overall Model):\n")
print(classification_report(y_train, ytrain_pred_best, digits=4))


# 8) Confusion Matrix for Train
cm = confusion_matrix(y_train, ytrain_pred_best)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format='d')
plt.title(f"Confusion Matrix - {best_overall_name}")
plt.show()


# 9) ROC Curve for Train
fpr, tpr, thresholds = roc_curve(y_train, ytrain_prob_best)
auc_best = roc_auc_score(y_train, ytrain_prob_best)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f"AUC = {auc_best:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve - {best_overall_name}")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()



y_pred_best = best_overall_model.predict(X_test)
y_prob_best = best_overall_model.predict_proba(X_test)[:, 1]

print("\nFinal Test Classification Report (Best Overall Model):\n")
print(classification_report(y_test, y_pred_best, digits=4))


# 10) Confusion Matrix for Test
cm = confusion_matrix(y_test, y_pred_best)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(values_format='d')
plt.title(f"Confusion Matrix - {best_overall_name}")
plt.show()


# 11) ROC Curve for Test
fpr, tpr, thresholds = roc_curve(y_test, y_prob_best)
auc_best = roc_auc_score(y_test, y_prob_best)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, label=f"AUC = {auc_best:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve - {best_overall_name}")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

"""NEW CODE

# GAUSSIAN NAIVE BAYES
"""

import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.experimental import enable_iterative_imputer  # noqa: F401
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import RandomOverSampler, SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.combine import SMOTEENN


# =========================================================
# Assumes you already have:
# X_train, X_test, y_train, y_test from train_test_split(...)
# =========================================================


# -----------------------------
# CV setup
# -----------------------------
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# -----------------------------
# GaussianNB hyperparameter grid
# -----------------------------
# var_smoothing adds a small value to variances for numerical stability.
# Tuning it can materially affect performance on some datasets.
param_grid = {
    "model__var_smoothing": np.logspace(-12, -6, 13)  # 1e-12 ... 1e-6
}

# -----------------------------
# Strategies (samplers)
# -----------------------------
strategies = {
    "1_no_resampling": None,
    "2_oversample_minority": RandomOverSampler(random_state=42),  # or SMOTE(random_state=42)
    "3_undersample_majority": RandomUnderSampler(random_state=42),
    "4_over_and_under_combined": SMOTEENN(random_state=42),       # combined
}

results = {}

# -----------------------------
# Run GridSearch for each strategy
# -----------------------------
for name, sampler in strategies.items():
    steps = [
        ("imputer", IterativeImputer(random_state=42)),
        # GaussianNB usually doesn't need scaling; keep pipeline simple.
        # If you want scaling, add: ("scaler", StandardScaler()),
    ]

    if sampler is not None:
        steps.append(("sampler", sampler))

    steps.append(("model", GaussianNB()))

    pipeline = ImbPipeline(steps=steps)

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        cv=skf,
        scoring="recall",   # for extreme imbalance, consider "average_precision" too
        n_jobs=-1,
        refit=True
    )

    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_

    # ---- Test predictions
    y_pred = best_model.predict(X_test)

    # GaussianNB supports predict_proba -> use for ROC/AUC
    y_prob = best_model.predict_proba(X_test)[:, 1]

    # ---- Metrics
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    auc = roc_auc_score(y_test, y_prob)
    fpr, tpr, _ = roc_curve(y_test, y_prob)

    results[name] = {
        "best_params": grid.best_params_,
        "best_cv_f1": grid.best_score_,
        "confusion_matrix": cm,
        "tn_fp_fn_tp": (tn, fp, fn, tp),
        "test_report": classification_report(y_test, y_pred, digits=4),
        "auc": auc,
        "roc": (fpr, tpr),
    }

# -----------------------------
# Print + Plot
# -----------------------------
for name, info in results.items():
    print("\n" + "=" * 75)
    print(f"Strategy: {name}")
    print(f"Best CV F1: {info['best_cv_f1']}")
    print(f"Best Params: {info['best_params']}")

    cm = info["confusion_matrix"]
    tn, fp, fn, tp = info["tn_fp_fn_tp"]
    print("\nConfusion Matrix:")
    print(cm)
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

    print("\nTest classification report:\n")
    print(info["test_report"])

    print(f"Test ROC-AUC: {info['auc']:.4f}")

    fpr, tpr = info["roc"]
    plt.figure()
    plt.plot(fpr, tpr, label=f"{name} (AUC={info['auc']:.4f})")
    plt.plot([0, 1], [0, 1], linestyle="--", label="Chance")
    plt.xlabel("False Positive Rate (FPR)")
    plt.ylabel("True Positive Rate (TPR)")
    plt.title(f"ROC Curve - {name}")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

import numpy as np
import matplotlib.pyplot as plt

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_auc_score,
    roc_curve
)

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.combine import SMOTEENN


# ============================================
# Best model from CV (Strategy 4)
# ============================================
final_model = ImbPipeline(steps=[
    ("imputer", IterativeImputer(random_state=42)),
    ("sampler", SMOTEENN(random_state=42)),
    ("model", GaussianNB(var_smoothing=1e-6))
])


# ============================================
# Fit on TRAIN
# ============================================
final_model.fit(X_train, y_train)


# ============================================
# Function to evaluate split
# ============================================
def evaluate_split(name, X, y, model):

    y_pred = model.predict(X)
    y_prob = model.predict_proba(X)[:, 1]

    cm = confusion_matrix(y, y_pred)
    tn, fp, fn, tp = cm.ravel()

    auc = roc_auc_score(y, y_prob)

    print("\n" + "="*70)
    print(f"{name} RESULTS")
    print("="*70)
    print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")
    print(f"ROC-AUC: {auc:.4f}\n")
    print(classification_report(y, y_pred, digits=4))

    # Plot confusion matrix
    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot(values_format="d")
    plt.title(f"{name} Confusion Matrix")
    plt.show()

    return auc


# ============================================
# Evaluate TRAIN and TEST
# ============================================
auc_train = evaluate_split("TRAIN", X_train, y_train, final_model)
auc_test  = evaluate_split("TEST",  X_test,  y_test,  final_model)


# ============================================
# Compare ROC Curves
# ============================================
y_prob_train = final_model.predict_proba(X_train)[:,1]
y_prob_test  = final_model.predict_proba(X_test)[:,1]

fpr_tr, tpr_tr, _ = roc_curve(y_train, y_prob_train)
fpr_te, tpr_te, _ = roc_curve(y_test, y_prob_test)

plt.figure()
plt.plot(fpr_tr, tpr_tr, label=f"Train ROC (AUC={auc_train:.4f})")
plt.plot(fpr_te, tpr_te, label=f"Test ROC (AUC={auc_test:.4f})")
plt.plot([0,1], [0,1], linestyle="--", label="Chance")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison (Train vs Test)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()